import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const dbUrl =
  process.env.POSTGRES_PRISMA_URL ||
  process.env.DATABASE_URL ||
  process.env.POSTGRES_URL_NON_POOLING ||
  process.env.POSTGRES_URL

const db = new PrismaClient({
  datasources: dbUrl ? { db: { url: dbUrl } } : undefined,
})

export const bookingHotels = [
  // ==========================================
  // MAKKAH (LA MECQUE) - 5 ÉTOILES (5*)
  // ==========================================
  {
    ville: 'Makkah',
    nom: 'Makkah Clock Royal Tower, A Fairmont Hotel',
    nomAr: 'فندق مكة كلوك رويال تاور، أحد فنادق فيرمونت',
    etoiles: 5,
    distanceHaram: 30,
    prixSingleSar: '2100',
    prixDoubleSar: '1849',
    prixTripleSar: '1550',
    prixQuadrupleSar: '1350',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Swissôtel Makkah',
    nomAr: 'سويس أوتيل مكة',
    etoiles: 5,
    distanceHaram: 50,
    prixSingleSar: '1350',
    prixDoubleSar: '950',
    prixTripleSar: '820',
    prixQuadrupleSar: '750',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Swissôtel Al Maqam Makkah',
    nomAr: 'سويس أوتيل المقام مكة',
    etoiles: 5,
    distanceHaram: 50,
    prixSingleSar: '1300',
    prixDoubleSar: '947',
    prixTripleSar: '810',
    prixQuadrupleSar: '740',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Raffles Makkah Palace',
    nomAr: 'رافلز قصر مكة',
    etoiles: 5,
    distanceHaram: 20,
    prixSingleSar: '2800',
    prixDoubleSar: '2200',
    prixTripleSar: '1900',
    prixQuadrupleSar: '1650',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Jabal Omar Hyatt Regency Makkah',
    nomAr: 'جبل عمر حياة ريجنسي مكة',
    etoiles: 5,
    distanceHaram: 100,
    prixSingleSar: '1250',
    prixDoubleSar: '947',
    prixTripleSar: '820',
    prixQuadrupleSar: '750',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Hilton Hotel & Convention Jabal Omar Makkah',
    nomAr: 'فندق ومركز مؤتمرات هيلتون جبل عمر مكة',
    etoiles: 5,
    distanceHaram: 250,
    prixSingleSar: '1200',
    prixDoubleSar: '935',
    prixTripleSar: '800',
    prixQuadrupleSar: '720',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Jumeirah Jabal Omar Makkah',
    nomAr: 'جميرا جبل عمر مكة',
    etoiles: 5,
    distanceHaram: 200,
    prixSingleSar: '1500',
    prixDoubleSar: '1140',
    prixTripleSar: '980',
    prixQuadrupleSar: '880',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Address Jabal Omar Makkah',
    nomAr: 'فندق العنوان جبل عمر مكة',
    etoiles: 5,
    distanceHaram: 250,
    prixSingleSar: '1400',
    prixDoubleSar: '1067',
    prixTripleSar: '920',
    prixQuadrupleSar: '830',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Conrad Jabal Omar Makkah',
    nomAr: 'كونراد جبل عمر مكة',
    etoiles: 5,
    distanceHaram: 200,
    prixSingleSar: '1600',
    prixDoubleSar: '1233',
    prixTripleSar: '1050',
    prixQuadrupleSar: '940',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Marriott Hotel Jabal Omar Makkah',
    nomAr: 'فندق ماريوت جبل عمر مكة',
    etoiles: 5,
    distanceHaram: 300,
    prixSingleSar: '1250',
    prixDoubleSar: '950',
    prixTripleSar: '820',
    prixQuadrupleSar: '740',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Pullman Zamzam Makkah',
    nomAr: 'بولمان زمزم مكة',
    etoiles: 5,
    distanceHaram: 50,
    prixSingleSar: '1300',
    prixDoubleSar: '900',
    prixTripleSar: '780',
    prixQuadrupleSar: '720',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Makkah Hotel & Towers',
    nomAr: 'فندق وأبراج مكة',
    etoiles: 5,
    distanceHaram: 60,
    prixSingleSar: '1150',
    prixDoubleSar: '800',
    prixTripleSar: '700',
    prixQuadrupleSar: '650',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Sheraton Makkah Jabal Al Kaaba',
    nomAr: 'شيراتون مكة جبل الكعبة',
    etoiles: 5,
    distanceHaram: 400,
    prixSingleSar: '900',
    prixDoubleSar: '650',
    prixTripleSar: '560',
    prixQuadrupleSar: '500',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'InterContinental Dar Al Tawhid Makkah',
    nomAr: 'دار التوحيد إنتركونتيننتال مكة',
    etoiles: 5,
    distanceHaram: 10,
    prixSingleSar: '2600',
    prixDoubleSar: '1950',
    prixTripleSar: '1650',
    prixQuadrupleSar: '1450',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Al Safwah Royale Orchid Hotel',
    nomAr: 'فندق الصفوة رويال أوركيد',
    etoiles: 5,
    distanceHaram: 20,
    prixSingleSar: '1200',
    prixDoubleSar: '850',
    prixTripleSar: '740',
    prixQuadrupleSar: '660',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Dorrar Aleiman Royal Hotel',
    nomAr: 'فندق درر الإيمان رويال مكة',
    etoiles: 5,
    distanceHaram: 30,
    prixSingleSar: '1100',
    prixDoubleSar: '780',
    prixTripleSar: '680',
    prixQuadrupleSar: '610',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Anjum Hotel Makkah',
    nomAr: 'فندق أنجم مكة',
    etoiles: 5,
    distanceHaram: 300,
    prixSingleSar: '950',
    prixDoubleSar: '680',
    prixTripleSar: '590',
    prixQuadrupleSar: '530',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Le Méridien Towers Makkah',
    nomAr: 'لو ميريديان تاورز مكة',
    etoiles: 5,
    distanceHaram: 600,
    prixSingleSar: '800',
    prixDoubleSar: '580',
    prixTripleSar: '500',
    prixQuadrupleSar: '450',
    devise: 'SAR',
    actif: true,
  },

  // ==========================================
  // MAKKAH (LA MECQUE) - 4 ÉTOILES (4*)
  // ==========================================
  {
    ville: 'Makkah',
    nom: 'Mövenpick Hotel & Residences Hajar Tower Makkah',
    nomAr: 'فندق ومقر إقامة موفنبيك برج هاجر مكة',
    etoiles: 4,
    distanceHaram: 50,
    prixSingleSar: '1350',
    prixDoubleSar: '1038',
    prixTripleSar: '890',
    prixQuadrupleSar: '790',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Hilton Suites Jabal Omar Makkah',
    nomAr: 'أجنحة هيلتون جبل عمر مكة',
    etoiles: 4,
    distanceHaram: 150,
    prixSingleSar: '1450',
    prixDoubleSar: '1148',
    prixTripleSar: '980',
    prixQuadrupleSar: '880',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'DoubleTree by Hilton Jabal Omar Makkah',
    nomAr: 'دبل تري من هيلتون جبل عمر مكة',
    etoiles: 4,
    distanceHaram: 300,
    prixSingleSar: '1150',
    prixDoubleSar: '918',
    prixTripleSar: '790',
    prixQuadrupleSar: '710',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Voco Makkah (an IHG Hotel)',
    nomAr: 'فوكو مكة (أحد فنادق IHG)',
    etoiles: 4,
    distanceHaram: 900,
    prixSingleSar: '550',
    prixDoubleSar: '400',
    prixTripleSar: '350',
    prixQuadrupleSar: '310',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Park Inn by Radisson Makkah Al Naseem',
    nomAr: 'بارك إن باي راديسون مكة النسيم',
    etoiles: 4,
    distanceHaram: 850,
    prixSingleSar: '480',
    prixDoubleSar: '360',
    prixTripleSar: '310',
    prixQuadrupleSar: '280',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Four Points by Sheraton Makkah Al Naseem',
    nomAr: 'فور بوينتس باي شيراتون مكة النسيم',
    etoiles: 4,
    distanceHaram: 850,
    prixSingleSar: '500',
    prixDoubleSar: '380',
    prixTripleSar: '330',
    prixQuadrupleSar: '290',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Millennium Makkah Al Naseem',
    nomAr: 'ميلينيوم مكة النسيم',
    etoiles: 4,
    distanceHaram: 800,
    prixSingleSar: '520',
    prixDoubleSar: '390',
    prixTripleSar: '340',
    prixQuadrupleSar: '300',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Copthorne Makkah Al Naseem',
    nomAr: 'كوبثورن مكة النسيم',
    etoiles: 4,
    distanceHaram: 850,
    prixSingleSar: '450',
    prixDoubleSar: '340',
    prixTripleSar: '300',
    prixQuadrupleSar: '270',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Al Kiswah Towers Hotel',
    nomAr: 'فندق أبراج الكسوة مكة',
    etoiles: 4,
    distanceHaram: 950,
    prixSingleSar: '400',
    prixDoubleSar: '300',
    prixTripleSar: '260',
    prixQuadrupleSar: '230',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Elaf Kinda Hotel',
    nomAr: 'فندق إيلاف كِندة مكة',
    etoiles: 4,
    distanceHaram: 100,
    prixSingleSar: '850',
    prixDoubleSar: '620',
    prixTripleSar: '540',
    prixQuadrupleSar: '480',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Makarem Ajyad Makkah Hotel',
    nomAr: 'فندق مكارم أجياد مكة',
    etoiles: 4,
    distanceHaram: 300,
    prixSingleSar: '750',
    prixDoubleSar: '540',
    prixTripleSar: '470',
    prixQuadrupleSar: '420',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Al Shohada Hotel Makkah',
    nomAr: 'فندق الشهداء مكة المكرمة',
    etoiles: 4,
    distanceHaram: 400,
    prixSingleSar: '700',
    prixDoubleSar: '510',
    prixTripleSar: '440',
    prixQuadrupleSar: '390',
    devise: 'SAR',
    actif: true,
  },

  // ==========================================
  // MAKKAH (LA MECQUE) - 3 ÉTOILES (3*)
  // ==========================================
  {
    ville: 'Makkah',
    nom: 'Le Méridien Makkah',
    nomAr: 'لو ميريديان مكة',
    etoiles: 3,
    distanceHaram: 150,
    prixSingleSar: '1100',
    prixDoubleSar: '905',
    prixTripleSar: '780',
    prixQuadrupleSar: '690',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Al Massa Hotel Makkah',
    nomAr: 'فندق الماسة مكة',
    etoiles: 3,
    distanceHaram: 200,
    prixSingleSar: '580',
    prixDoubleSar: '420',
    prixTripleSar: '360',
    prixQuadrupleSar: '320',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Elaf Al Mashaer Hotel Makkah',
    nomAr: 'فندق إيلاف المشاعر مكة',
    etoiles: 3,
    distanceHaram: 400,
    prixSingleSar: '520',
    prixDoubleSar: '380',
    prixTripleSar: '330',
    prixQuadrupleSar: '290',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Al Safwa Hotel Orchid',
    nomAr: 'فندق الصفوة أوركيد مكة',
    etoiles: 3,
    distanceHaram: 50,
    prixSingleSar: '750',
    prixDoubleSar: '550',
    prixTripleSar: '480',
    prixQuadrupleSar: '430',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Retaj Al Rayyan Makkah',
    nomAr: 'فندق ريتاج الريان مكة',
    etoiles: 3,
    distanceHaram: 750,
    prixSingleSar: '380',
    prixDoubleSar: '270',
    prixTripleSar: '230',
    prixQuadrupleSar: '200',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Dar Al Eiman Grand',
    nomAr: 'فندق دار الإيمان جراند مكة',
    etoiles: 3,
    distanceHaram: 650,
    prixSingleSar: '420',
    prixDoubleSar: '310',
    prixTripleSar: '270',
    prixQuadrupleSar: '240',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Al Manar Hotel Makkah',
    nomAr: 'فندق المنار مكة المكرمة',
    etoiles: 3,
    distanceHaram: 600,
    prixSingleSar: '350',
    prixDoubleSar: '250',
    prixTripleSar: '210',
    prixQuadrupleSar: '180',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Rehab Al Noor Hotel',
    nomAr: 'فندق رحاب النور مكة',
    etoiles: 3,
    distanceHaram: 700,
    prixSingleSar: '320',
    prixDoubleSar: '230',
    prixTripleSar: '195',
    prixQuadrupleSar: '170',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Olayan Plaza Hotel Makkah',
    nomAr: 'فندق عليان بلازا مكة',
    etoiles: 3,
    distanceHaram: 900,
    prixSingleSar: '300',
    prixDoubleSar: '220',
    prixTripleSar: '185',
    prixQuadrupleSar: '160',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Makkah',
    nom: 'Mira Ajyad Hotel Makkah',
    nomAr: 'فندق ميرا أجياد مكة',
    etoiles: 3,
    distanceHaram: 350,
    prixSingleSar: '450',
    prixDoubleSar: '330',
    prixTripleSar: '280',
    prixQuadrupleSar: '250',
    devise: 'SAR',
    actif: true,
  },

  // ==========================================
  // MEDINE (MÉDINE) - 5 ÉTOILES (5*)
  // ==========================================
  {
    ville: 'Medine',
    nom: 'The Oberoi Madina',
    nomAr: 'فندق أوبروي المدينة',
    etoiles: 5,
    distanceHaram: 30,
    prixSingleSar: '1800',
    prixDoubleSar: '1300',
    prixTripleSar: '1100',
    prixQuadrupleSar: '980',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Sofitel Shahd Al Madinah',
    nomAr: 'فندق سوفيتيل شهد المدينة',
    etoiles: 5,
    distanceHaram: 50,
    prixSingleSar: '1150',
    prixDoubleSar: '842',
    prixTripleSar: '730',
    prixQuadrupleSar: '650',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Dar Al Taqwa Hotel Madinah',
    nomAr: 'فندق دار التقوى المدينة المنورة',
    etoiles: 5,
    distanceHaram: 20,
    prixSingleSar: '1500',
    prixDoubleSar: '1050',
    prixTripleSar: '900',
    prixQuadrupleSar: '820',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Anwar Al Madinah Mövenpick Hotel',
    nomAr: 'فندق أنوار المدينة موفنبيك',
    etoiles: 5,
    distanceHaram: 50,
    prixSingleSar: '1100',
    prixDoubleSar: '780',
    prixTripleSar: '680',
    prixQuadrupleSar: '620',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Pullman Zamzam Madina',
    nomAr: 'بولمان زمزم المدينة',
    etoiles: 5,
    distanceHaram: 150,
    prixSingleSar: '1000',
    prixDoubleSar: '720',
    prixTripleSar: '620',
    prixQuadrupleSar: '560',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Shaza Madinah',
    nomAr: 'فندق شذا المدينة',
    etoiles: 5,
    distanceHaram: 120,
    prixSingleSar: '1250',
    prixDoubleSar: '880',
    prixTripleSar: '760',
    prixQuadrupleSar: '690',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Madinah Hilton Hotel',
    nomAr: 'فندق هيلتون المدينة',
    etoiles: 5,
    distanceHaram: 80,
    prixSingleSar: '1150',
    prixDoubleSar: '820',
    prixTripleSar: '710',
    prixQuadrupleSar: '640',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Crowne Plaza Madinah (IHG Hotel)',
    nomAr: 'فندق كراون بلازا المدينة (أحد فنادق IHG)',
    etoiles: 5,
    distanceHaram: 150,
    prixSingleSar: '950',
    prixDoubleSar: '680',
    prixTripleSar: '590',
    prixQuadrupleSar: '530',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Frontel Al Harithia Hotel',
    nomAr: 'فندق فرونتل الحارثية المدينة',
    etoiles: 5,
    distanceHaram: 120,
    prixSingleSar: '880',
    prixDoubleSar: '620',
    prixTripleSar: '540',
    prixQuadrupleSar: '490',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Dar Al Iman InterContinental Madinah',
    nomAr: 'فندق دار الإيمان إنتركونتيننتال المدينة',
    etoiles: 5,
    distanceHaram: 20,
    prixSingleSar: '1600',
    prixDoubleSar: '1150',
    prixTripleSar: '990',
    prixQuadrupleSar: '890',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Le Méridien Medina',
    nomAr: 'لو ميريديان المدينة',
    etoiles: 5,
    distanceHaram: 900,
    prixSingleSar: '750',
    prixDoubleSar: '540',
    prixTripleSar: '470',
    prixQuadrupleSar: '410',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Madinah Marriott Hotel',
    nomAr: 'فندق ماريوت المدينة',
    etoiles: 5,
    distanceHaram: 500,
    prixSingleSar: '850',
    prixDoubleSar: '600',
    prixTripleSar: '520',
    prixQuadrupleSar: '460',
    devise: 'SAR',
    actif: true,
  },

  // ==========================================
  // MEDINE (MÉDINE) - 4 ÉTOILES (4*)
  // ==========================================
  {
    ville: 'Medine',
    nom: 'Makarem Burj Al Madinah',
    nomAr: 'فندق مكارم برج المدينة',
    etoiles: 4,
    distanceHaram: 100,
    prixSingleSar: '950',
    prixDoubleSar: '698',
    prixTripleSar: '600',
    prixQuadrupleSar: '540',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Diyar Ajwa, Tapestry Collection by Hilton',
    nomAr: 'ديار عجوة، من فنادق تابستري كوليكشن باي هيلتون',
    etoiles: 4,
    distanceHaram: 150,
    prixSingleSar: '1300',
    prixDoubleSar: '1020',
    prixTripleSar: '880',
    prixQuadrupleSar: '790',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Taiba Front Hotel',
    nomAr: 'فندق واجهة طيبة المدينة',
    etoiles: 4,
    distanceHaram: 80,
    prixSingleSar: '650',
    prixDoubleSar: '480',
    prixTripleSar: '420',
    prixQuadrupleSar: '380',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Elaf Taiba Hotel',
    nomAr: 'فندق إيلاف طيبة المدينة',
    etoiles: 4,
    distanceHaram: 120,
    prixSingleSar: '890',
    prixDoubleSar: '675',
    prixTripleSar: '580',
    prixQuadrupleSar: '520',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Saja Al Madinah',
    nomAr: 'فندق سجى المدينة المنورة',
    etoiles: 4,
    distanceHaram: 250,
    prixSingleSar: '500',
    prixDoubleSar: '380',
    prixTripleSar: '330',
    prixQuadrupleSar: '290',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Al Aqeeq Madinah Hotel',
    nomAr: 'فندق العقيق المدينة',
    etoiles: 4,
    distanceHaram: 100,
    prixSingleSar: '780',
    prixDoubleSar: '560',
    prixTripleSar: '490',
    prixQuadrupleSar: '430',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Ruve Al Madinah Hotel',
    nomAr: 'فندق روف المدينة المنورة',
    etoiles: 4,
    distanceHaram: 200,
    prixSingleSar: '680',
    prixDoubleSar: '490',
    prixTripleSar: '420',
    prixQuadrupleSar: '380',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Zaha Al Madinah Hotel',
    nomAr: 'فندق زها المدينة',
    etoiles: 4,
    distanceHaram: 700,
    prixSingleSar: '420',
    prixDoubleSar: '310',
    prixTripleSar: '270',
    prixQuadrupleSar: '240',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Grand Plaza Madinah Hotel',
    nomAr: 'فندق جراند بلازا المدينة',
    etoiles: 4,
    distanceHaram: 300,
    prixSingleSar: '580',
    prixDoubleSar: '420',
    prixTripleSar: '360',
    prixQuadrupleSar: '320',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Boutique Khan Atrah',
    nomAr: 'بوتيك خان عطره المدينة',
    etoiles: 4,
    distanceHaram: 650,
    prixSingleSar: '980',
    prixDoubleSar: '738',
    prixTripleSar: '640',
    prixQuadrupleSar: '570',
    devise: 'SAR',
    actif: true,
  },

  // ==========================================
  // MEDINE (MÉDINE) - 3 ÉTOILES (3*)
  // ==========================================
  {
    ville: 'Medine',
    nom: 'Bosphorus Hotel Medina',
    nomAr: 'فندق البوسفور المدينة',
    etoiles: 3,
    distanceHaram: 250,
    prixSingleSar: '620',
    prixDoubleSar: '457',
    prixTripleSar: '390',
    prixQuadrupleSar: '350',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Bosphorus Hotel Waqf Safi',
    nomAr: 'فندق البوسفور وقف الصافي',
    etoiles: 3,
    distanceHaram: 300,
    prixSingleSar: '550',
    prixDoubleSar: '404',
    prixTripleSar: '350',
    prixQuadrupleSar: '310',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Golden Tulip Al-Zahabi',
    nomAr: 'فندق جولدن توليب الذهبي المدينة',
    etoiles: 3,
    distanceHaram: 100,
    prixSingleSar: '630',
    prixDoubleSar: '467',
    prixTripleSar: '400',
    prixQuadrupleSar: '360',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Tulip Inn Al Daar Rawafid',
    nomAr: 'فندق توليب إن الدار روافد المدينة',
    etoiles: 3,
    distanceHaram: 200,
    prixSingleSar: '700',
    prixDoubleSar: '521',
    prixTripleSar: '450',
    prixQuadrupleSar: '400',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Mysk Al Balad',
    nomAr: 'فندق مسك البلد المدينة المنورة',
    etoiles: 3,
    distanceHaram: 200,
    prixSingleSar: '750',
    prixDoubleSar: '554',
    prixTripleSar: '480',
    prixQuadrupleSar: '420',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Emaar Al Mektan Hotel',
    nomAr: 'فندق إعمار المكتان المدينة',
    etoiles: 3,
    distanceHaram: 180,
    prixSingleSar: '780',
    prixDoubleSar: '584',
    prixTripleSar: '500',
    prixQuadrupleSar: '450',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Emaar Royal Hotel Madinah',
    nomAr: 'فندق إعمار رويال المدينة المنورة',
    etoiles: 3,
    distanceHaram: 150,
    prixSingleSar: '800',
    prixDoubleSar: '601',
    prixTripleSar: '520',
    prixQuadrupleSar: '460',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'New Madinah Hotel',
    nomAr: 'فندق نيو مدينا المدينة',
    etoiles: 3,
    distanceHaram: 250,
    prixSingleSar: '780',
    prixDoubleSar: '584',
    prixTripleSar: '500',
    prixQuadrupleSar: '450',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Nozul Al Rawda (ex Al Aqeeq)',
    nomAr: 'فندق نزل الروضة المدينة المنورة',
    etoiles: 3,
    distanceHaram: 350,
    prixSingleSar: '350',
    prixDoubleSar: '245',
    prixTripleSar: '210',
    prixQuadrupleSar: '190',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Al Rawda Royal Inn',
    nomAr: 'فندق الروضة رويال إن المدينة',
    etoiles: 3,
    distanceHaram: 80,
    prixSingleSar: '650',
    prixDoubleSar: '480',
    prixTripleSar: '410',
    prixQuadrupleSar: '370',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Concorde Dar Al Khair Hotel',
    nomAr: 'فندق كونكورد دار الخير المدينة',
    etoiles: 3,
    distanceHaram: 150,
    prixSingleSar: '550',
    prixDoubleSar: '400',
    prixTripleSar: '350',
    prixQuadrupleSar: '310',
    devise: 'SAR',
    actif: true,
  },
  {
    ville: 'Medine',
    nom: 'Al Mukhtara International Hotel',
    nomAr: 'فندق المختارة العالمي المدينة',
    etoiles: 3,
    distanceHaram: 300,
    prixSingleSar: '420',
    prixDoubleSar: '300',
    prixTripleSar: '260',
    prixQuadrupleSar: '230',
    devise: 'SAR',
    actif: true,
  },
]

async function populateHotels() {
  console.log(`🏨 Début de la mise à jour du catalogue d'hôtels (${bookingHotels.length} hôtels)...`)

  // 1. Delete previous hotels
  const deleted = await db.catalogueHotel.deleteMany()
  console.log(`🗑️ ${deleted.count} anciens hôtels supprimés.`)

  // 2. Insert all new booking hotels
  const result = await db.catalogueHotel.createMany({
    data: bookingHotels,
  })

  console.log(`✨ ${result.count} hôtels de Booking.com créés avec succès !`)

  const totalMakkah = await db.catalogueHotel.count({ where: { ville: 'Makkah' } })
  const totalMedine = await db.catalogueHotel.count({ where: { ville: 'Medine' } })
  console.log(`- Total Makkah : ${totalMakkah}`)
  console.log(`- Total Médine : ${totalMedine}`)
  console.log(`- Total Général : ${totalMakkah + totalMedine}`)
}

populateHotels()
  .then(async () => {
    await db.$disconnect()
    process.exit(0)
  })
  .catch(async (err) => {
    console.error('❌ Erreur:', err)
    await db.$disconnect()
    process.exit(1)
  })
